applications/persona/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'persona_app'

urlpatterns = [
    path('', views.InicioView.as_view(), name='inicio'),
    path('listar-empleados/', views.ListAllEmpleados.as_view(), name="empleados_all"),
    path('lista-empleados-admin/', views.ListEmpleadosAdmin.as_view(), name="empleados_admin"),
    path('lista-by-area/<shortname>', views.ListByAreaEmpleados.as_view(), name="empleados_por_departamento"),
    path('lista-by-trabajo/<job>', views.ListByJobEmpleado.as_view()),
    path('buscar-empleado/', views.ListEmpleadoByKword.as_view()),
    path('habilidades/<id>', views.ListHabilidadesEmpleado.as_view()),
    path('ver-detalle-empleado/<pk>', views.EmpleadoDetailView.as_view(), name="ver_empleado"),
    path('add-empleado/', views.EmpleadoCreateView.as_view(), name="add_empleado"),
    path('success/', views.SuccessView.as_view(), name='correcto'),
    path('update-empleado/<pk>', views.EmpleadoUpdateView.as_view(), name='modificar_empleado'),
    path('delete-empleado/<pk>', views.EmpleadoDeleteView.as_view(), name='eliminar_empleado'),
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

# importar paquetes para uso de archivos
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # incluimos las urls de la app departamento
    re_path('', include('applications.departamento.urls')),
    # incluimos las urls de la app persona
    re_path('', include('applications.persona.urls')),
    # incluimos las urls de la app home
    re_path('', include('applications.home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/persona/models.py
from django.db import models
from applications.departamento.models import Departamento
from ckeditor.fields import RichTextField

# Create your models here.

class Habilidades(models.Model):
    habilidad = models.CharField('Habilidad', max_length=50)

    class Meta:
        verbose_name = 'Habilidad'
        verbose_name_plural = 'Habilidades Empleado'

    def __str__(self):
        return self.habilidad


class Empleado(models.Model):
    """ modelo para la tabla empleado """
    
    # Solo tendremos trabajos especificos
    # Contador
    # Administrador
    # Economista
    # Otro
    JOB_CHOICES = (
        ('0', 'CONTADOR'),
        ('1', 'ADMINISTRADOR'),
        ('2', 'ECONOMISTA'),
        ('3', 'OTRO'),
    )

    firt_name = models.CharField('Nombres', max_length=60)
    last_name = models.CharField('Apellidos', max_length=60)
    full_name = models.CharField('Nombre Completo', max_length=120, blank=True)
    job = models.CharField('Trabajo', max_length=50, choices=JOB_CHOICES)
    # creamos nuestra relación
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    # relación mucho a mucho
    habilidades = models.ManyToManyField(Habilidades)
    #hoja_vidal = RichTextField()
    avatar = models.ImageField(upload_to='empleado', blank=True, null=True, height_field=None, width_field=None, max_length=100)
    class Meta:
        verbose_name = 'Mi Empleado'
        verbose_name_plural = 'Empleados de la empresa'
        ordering = ['-firt_name']
        # validar que no exista una combinacion similar
        unique_together = ('firt_name', 'last_name')

    def __str__(self):
        return str(self.id) + ' - ' + self.firt_name + ' - ' + self.last_name

applications/persona/forms.py
from django import forms
from .models import Empleado

class CrearEmpleadoForm(forms.ModelForm):
    """Formulario para crear un empleado."""

    class Meta:
        model = Empleado
        fields = (
            'firt_name', 
            'last_name',
            'full_name',
            'job',
            'departamento',
            'habilidades',
            'avatar'
        )
        widgets = {
            'habilidades': forms.CheckboxSelectMultiple()
        }

applications/persona/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, TemplateView, UpdateView, DeleteView
# models
from .models import Empleado
# form
from .forms import CrearEmpleadoForm

# Create your views here.

class InicioView(TemplateView):
    """ vista que carga la pagina de inicio """
    template_name = "inicio.html"


class ListAllEmpleados(ListView):
    """ listar todos los empleados de la empresa """
    template_name = 'persona/list_all.html'
    paginate_by = 3
    ordering = 'firt_name'
    #model = Empleado
    context_object_name = 'empleados'
    def get_queryset(self):
        palabra_clave = self.request.GET.get("kword", '')
        lista = Empleado.objects.filter(full_name__icontains = palabra_clave)
        return lista


class ListEmpleadosAdmin(ListView):
    """ listar todos los empleados de la empresa """
    template_name = 'persona/list_empleados.html'
    paginate_by = 4
    ordering = 'firt_name'
    model = Empleado
    context_object_name = 'empleados'


class ListByAreaEmpleados(ListView):
    """ listar todos los empleados que pertenecen a un area de la empresa """
    template_name = 'persona/list_by_area.html'
    model = Empleado
    context_object_name = "empleados"
    def get_queryset(self):
        # obtener valor parametro url
        area = self.kwargs['shortname']
        lista =Empleado.objects.filter(departamento__short_name = area)
        return lista


class ListByJobEmpleado(ListView):
    """ listar empleados por trabajo """
    template_name = 'persona/list_by_trabajo.html'
    model = Empleado

    def get_queryset(self):
        trabajo = self.kwargs['job']
        lista = Empleado.objects.filter(job = trabajo)
        return lista


class ListEmpleadoByKword(ListView):
    """ lista los empleados por palabra clave (info viene desde un formulario) """
    template_name = 'persona/by_kword.html'
    context_object_name = 'empleados'
    
    def get_queryset(self):
        palabra_clave = self.request.GET.get("kword", '')
        lista = Empleado.objects.filter(firt_name = palabra_clave)
        return lista


class ListHabilidadesEmpleado(ListView):
    """ lista todas las habilidades de un empleado """
    template_name = 'persona/habilidades_empleado.html'
    model = Empleado
    context_object_name = 'habilidades'

    def get_queryset(self):
        id = self.kwargs['id']
        empleado = Empleado.objects.get(id = id)
        return empleado.habilidades.all()


# ver en detalle un registro
class EmpleadoDetailView(DetailView):
    model = Empleado
    template_name = "persona/detail_empleado.html"
    context_object_name = 'empleado'
    
    def get_context_data(self, **kwargs):
        context = super(EmpleadoDetailView, self).get_context_data(**kwargs)
        # generando algun logica proceso
        context['titulo'] = 'ejm. context'
        return context



class SuccessView(TemplateView):
    template_name = "persona/success.html"



class EmpleadoCreateView(CreateView):
    model = Empleado
    form_class = CrearEmpleadoForm
    template_name = "persona/add.html"
    """
    fields = [
        'firt_name',
        'last_name',
        'job',
        'departamento',
        'habilidades',
        'avatar'
    ]
    """
    #fields = ('__all__')
    #success_url = '.' # la misma pagina, redireccionar cuando esta todo correcto
    #success_url = '/success/'
    success_url = reverse_lazy('persona_app:correcto')

    def form_valid(self, form):
        """ If the form is valid, save the associated model. """
        #logica del proceso
        #empleado = form.save()
        empleado = form.save(commit=False)
        empleado.full_name = empleado.firt_name + ' ' + empleado.last_name
        empleado.save()
        return super(EmpleadoCreateView, self).form_valid(form)



class EmpleadoUpdateView(UpdateView):
    model = Empleado
    template_name = "persona/update.html"
    form_class = CrearEmpleadoForm
    """
    fields = [
        'firt_name',
        'last_name',
        'job',
        'departamento',
        'habilidades',
        'avatar'
    ]
    """
    success_url = reverse_lazy('persona_app:empleados_admin')

    def post(self, request, *args, **kwargs):
        """ Handle POST requests: instantiate a form instance with the passed
            POST variables and then check if it's valid. """
        self.object = self.get_object()
        print("************* METODO POST **************")
        print(request)
        print(request.POST['last_name'])
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        """ If the form is valid, save the associated model. """
        #logica del proceso
        #empleado = form.save()
        print('====================================================')
        print('#=========== MODIFICAR EMPLEADO ===================#')
        empleado = form.save(commit=False)
        empleado.full_name = empleado.firt_name + ' ' + empleado.last_name
        empleado.save()
        return super(EmpleadoUpdateView, self).form_valid(form)


class EmpleadoDeleteView(DeleteView):
    model = Empleado
    template_name = "persona/delete.html"
    context_object_name = 'empleado'

    def delete(self, request, *args, **kwargs):
        """
        Call the delete() method on the fetched object and then redirect to the
        success URL.
        """
        self.object = self.get_object()
        self.object.delete()
        return HttpResponseRedirect(reverse_lazy('persona_app:empleados_admin'))

templates/persona/add.html
{% extends 'base.html' %}
{% block title %} Registrar Empleado {% endblock title %}
{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Registrar Empleado</h1>
        <div class="cell callout">
            <form class="grid-x grid-margin-x" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="medium-6 cell">
                    <label>Nombres
                        {{ form.firt_name }}
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>Apellidos
                        {{ form.last_name }}
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>Trabajo
                        {{ form.job }}
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>Departamento
                        {{ form.departamento }}
                    </label>
                </div>
                <div class="medium-12 cell">
                    <label>Habilidades
                        {{ form.habilidades }}
                    </label>
                </div>
                <div class="medium-12 cell">
                    <!--<label for="exampleFileUpload" class="button">Avatar</label>-->
                    <!--<input type="file" id="exampleFileUpload" class="show-for-sr">-->
                    <label>Avatar</label>
                    {{ form.avatar }}
                </div>
                <div class="medium-6 cell">
                    <button class="success button" type="submit" >Agregar Nuevo Empleado</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/persona/by_kword.html
<h1>Buscar empleado por palabra clave</h1>
<form method="GET">
    <!-- comunicacion segura -->
    {% csrf_token %}
    <input name="kword" id="kword" placeholder="ingresar nombre aquí" >
    <button type="submit">Buscar</button>
</form>
<h3>Listado de empleados</h3>
<ul>
    {% for empleado in object_list  %}
        <li>{{ empleado.firt_name }}</li>
    {% endfor %}    
</ul>

templates/persona/delete.html
{% extends 'base.html' %}
{% block title %} Editar Empleado {% endblock title %}
{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Eliminar Empleado</h1>
        <form class="cell" method="POST">
            {% csrf_token %}
            <div class="callout secondary">
                <h5>¿Seguro que desea eliminar al empleado {{ empleado.firt_name }} {{ empleado.last_name }}?</h5>
                
                <div class="small button-group">
                    <button class="alert button" type="submit" >Confirmar</button>
                    &nbsp;
                    <a href="{% url 'persona_app:empleados_admin' %}" class="success button" type="button" >Volver</a>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

templates/persona/detail_empleado.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    {% include 'includes/header.html' %}    
    <br>
    <div class="grid-x align-center">
        <div class="cell" style="width: 300px;">
            <div class="radius bordered shadow card card-image">
                {% if empleado.avatar %}
                    <img src="{{ empleado.avatar.url }} ">
                {% else %}
                    <img src="{% static 'img/no_photo.png' %}">
                {% endif %}
            <div class="card-divider">
                {{ empleado.get_job_display }} | {{ titulo }}
            </div>
            <div class="card-section">
                <p><b>{{ empleado.firt_name }} {{ empleado.last_name }}</b></p>
                {{ empleado.departamento.name }} | {{ empleado.departamento.short_name }}
                <h6>Habilidades</h6>
                <div class="small warning button-group">
                    {% for habilidad in empleado.habilidades.all %}                        
                        <a class="button">{{ habilidad }}</a>
                        {% empty %}
                        (sin registrar)
                    {% endfor %}
                </div>
                </ul>
                <a href="{% url 'persona_app:empleados_all' %}" class="button expanded">Volver</a>
            </div>
        </div>
    </div>
{% endblock content %}

templates/persona/habilidades_empleado.html
<h1>Habilidades del empleado</h1>
<ul>
    {% for habilidad in object_list  %}
        <li>{{ habilidad }}</li>
    {% endfor %}    
</ul>

templates/persona/list_all.html
{% extends 'base.html' %}

{% block title %} Lista Empleados {% endblock title %}
    
{% block content %}
{% include 'includes/header.html' %}
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Listado de Empleados</h1>
                <form method="GET" class="cell grid-x grid-margin-x">
                    {% csrf_token %}
                    <div class="cell large-7">
                        <input type="text" id="kword" name="kword" placeholder="Buscar empleado" name="buscador"></inpu>
                    </div>
                    <div class="cell large-2">  
                        <button type="submit" class="success button">Buscar</button>
                    </div>
                </form>
            <div class="cell">
                <table>
                    <thead>
                      <tr>
                        <th>ID</th>
                        <th>Nombres</th>
                        <th>Apellidos</th>
                        <th>Departamentos</th>
                        <th>Acciones</th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for empleado in  empleados %}
                            <tr>    
                                <td>{{ empleado.id }}</td>
                                <td>{{ empleado.firt_name }}</td>
                                <td>{{ empleado.last_name }}</td>
                                <td>{{ empleado.departamento.name }} | {{ empleado.departamento.short_name }}</td>
                                <td>
                                    <a class="button warning" href="{% url 'persona_app:ver_empleado' empleado.id %}">Ver</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="cell">
                {% if is_paginated %}
                <nav aria-label="Pagination">
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li class="pagination-previous">
                                <a href="?page={{ page_obj.previous_page_number }}">atras</a>
                            </li>
                        {% endif %}
                        <!--<li class="current"><span class="show-for-sr">You're on page</span> 1</li>-->
                        
                        {% for page in paginator.page_range %}                  
                            {% ifequal page page_obj.number  %} 
                            <li class="current"><span class="show-for-sr"></span> {{ page }}</li>
                            {% else %}
                            <li><a href="?page={{ page }}" aria-label="Page 2">{{ page }}</a></li>
                            {% endifequal %}
                        {% endfor %}

                        {% if page_obj.has_next %}
                        <li class="pagination-next">
                            <a href="?page={{ page_obj.next_page_number }}" aria-label="Next page">Siguiente</a>
                        </li>
                        {% endif %}

                        <span class="current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>
                    </ul>
                </nav>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}

templates/persona/list_by_area.html
{% extends 'base.html' %}
{% block title %} Lista Empleados Por Departamento {% endblock title %}
{% block content %}
{% include 'includes/header.html' %}
<br>
<div class="grid-container">
    <div class="grid-x">
        <table>
            <thead>
                <tr>
                <th>ID</th>
                <th>Nombres</th>
                <th>Apellidos</th>
                <th>Departamentos</th>
                <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for empleado in  empleados %}
                <tr>
                    <td>{{ empleado.id }}</td>
                    <td>{{ empleado.firt_name }}</td>
                    <td>{{ empleado.last_name }}</td>
                    <td>{{ empleado.departamento.name }} | {{ empleado.departamento.short_name }}</td>
                    <td>
                        <a class="button warning" href="{% url 'persona_app:ver_empleado' empleado.id %}">Ver</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock content %}

templates/persona/list_by_trabajo.html
<h1>Listado empleados por trabajo</h1>
<ul>
    {% for empleado in object_list %}
        <li>{{ empleado.firt_name }}</li>
    {% endfor %}
</ul>

templates/persona/list_empleados.html
{% extends 'base.html' %}
{% block title %} Lista Empleados {% endblock title %}
{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1>Todos los empleados registrados</h1>
        <div class="cell">
            <table>
                <thead>
                    <tr>
                    <th>ID</th>
                    <th>Nombres</th>
                    <th>Apellidos</th>
                    <th>Departamentos</th>
                    <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for empleado in  empleados %}
                        <tr>    
                            <td>{{ empleado.id }}</td>
                            <td>{{ empleado.firt_name }}</td>
                            <td>{{ empleado.last_name }}</td>
                            <td>{{ empleado.departamento.name }} | {{ empleado.departamento.short_name }}</td>
                            <td>
                                <a class="button" href="{% url 'persona_app:modificar_empleado' empleado.id %}">Editar</a>
                                <a class="button alert" href="{% url 'persona_app:eliminar_empleado' empleado.id %}">Eliminar</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="cell">
            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="pagination-previous">
                            <a href="?page={{ page_obj.previous_page_number }}">atras</a>
                        </li>
                    {% endif %}
                    <!--<li class="current"><span class="show-for-sr">You're on page</span> 1</li>-->
                    
                    {% for page in paginator.page_range %}                  
                        {% ifequal page page_obj.number  %} 
                        <li class="current"><span class="show-for-sr"></span> {{ page }}</li>
                        {% else %}
                        <li><a href="?page={{ page }}" aria-label="Page 2">{{ page }}</a></li>
                        {% endifequal %}
                    {% endfor %}

                    {% if page_obj.has_next %}
                    <li class="pagination-next">
                        <a href="?page={{ page_obj.next_page_number }}" aria-label="Next page">Siguiente</a>
                    </li>
                    {% endif %}

                    <span class="current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
                </ul>
            </nav>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

templates/persona/success.html
{% extends 'base.html' %}
{% block title %} Pagina Exito {% endblock title %}
{% block content %}
{% include 'includes/header.html' %}
<br>
<div class="grid-container">
    <div class="grid-x">
            <div class="medium-12 cell">
                <div class="callout success">
                    <h5>Felicitaciones, se guardo correctamente el empleado.</h5>
                    <a href="{% url 'persona_app:empleados_all' %}" class="button" type="submit" >Volver listado empleados</a>
                </div>
            </div>
    </div>
</div>
{% endblock content %}

templates/persona/update.html
{% extends 'base.html' %}
{% block title %} Editar Empleado {% endblock title %}
{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Modificar datos empleado</h1>
        <div class="cell callout">
            <form class="grid-x grid-margin-x" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="medium-6 cell">
                    <label>Nombres
                        {{ form.firt_name }}
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>Apellidos
                        {{ form.last_name }}
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>Trabajo
                        {{ form.job }}
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>Departamento
                        {{ form.departamento }}
                    </label>
                </div>
                <div class="medium-12 cell">
                    <label>Habilidades
                        {{ form.habilidades }}
                    </label>
                </div>
                <div class="medium-12 cell">
                    <label>Avatar
                        {{ form.avatar }}
                    </label>
                </div>
                <div class="medium-6 cell">
                    <button class="button success" type="submit" >Actualizar</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}