applications/departamento/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'departamento_app'

urlpatterns = [
    path('add-departamento/', views.NewDepartamentoView.as_view(), name='ingresar_departamento'),
    path('listar-departamentos/', views.DepartamentoListView.as_view(), name="departamento_all"),
]

applications/persona/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'persona_app'

urlpatterns = [
    path('', views.InicioView.as_view(), name='inicio'),
    path('listar-empleados/', views.ListAllEmpleados.as_view(), name="empleados_all"),
    path('lista-empleados-admin/', views.ListEmpleadosAdmin.as_view(), name="empleados_admin"),
    path('lista-by-area/<shortname>', views.ListByAreaEmpleados.as_view(), name="empleados_por_departamento"),
    path('lista-by-trabajo/<job>', views.ListByJobEmpleado.as_view()),
    path('buscar-empleado/', views.ListEmpleadoByKword.as_view()),
    path('habilidades/<id>', views.ListHabilidadesEmpleado.as_view()),
    path('ver-detalle-empleado/<pk>', views.EmpleadoDetailView.as_view(), name="ver_empleado"),
    path('add-empleado/', views.EmpleadoCreateView.as_view(), name="add_empleado"),
    path('success/', views.SuccessView.as_view(), name='correcto'),
    path('update-empleado/<pk>', views.EmpleadoUpdateView.as_view(), name='modificar_empleado'),
    path('delete-empleado/<pk>', views.EmpleadoDeleteView.as_view(), name='eliminar_empleado'),
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

# importar paquetes para uso de archivos
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # incluimos las urls de la app departamento
    re_path('', include('applications.departamento.urls')),
    # incluimos las urls de la app persona
    re_path('', include('applications.persona.urls')),
    # incluimos las urls de la app home
    re_path('', include('applications.home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/header.html
<div class="top-bar">
    <div class="top-bar-left">
        <ul class="dropdown menu align-right" data-dropdown-menu>
            <li class=""><a href="/">Home</a></li>
            <li><a href="{% url 'persona_app:empleados_all' %}">Empleados</a></li>
            <li><a href="{% url 'departamento_app:departamento_all' %}">Departamentos</a></li>
            <li><a href="{% url 'persona_app:empleados_admin' %}">Administrar</a></li>
            <li>
                <a href="#">Registrar Nuevo</a>
                <ul class="menu">
                    <li><a href="{% url 'persona_app:add_empleado' %}">Empleado</a></li>
                    <li><a href="{% url 'departamento_app:ingresar_departamento' %}">Departamento</a></li>
                    <!-- ... -->
                </ul>
            </li>
        </ul>
    </div>
    <div class="top-bar-right">
        <ul class="menu">
        <li><input type="search" placeholder="Buscar"></li>
        <li><a href="#" type="button" class="button">Buscar</a></li>
        </ul>
    </div>
</div>