applications/departamento/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'departamento_app'

urlpatterns = [
    path('add-departamento/', views.NewDepartamentoView.as_view(), name='ingresar_departamento'),
    path('listar-departamentos/', views.DepartamentoListView.as_view(), name="departamento_all"),
]

applications/persona/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'persona_app'

urlpatterns = [
    path('', views.InicioView.as_view(), name='inicio'),
    path('listar-empleados/', views.ListAllEmpleados.as_view(), name="empleados_all"),
    path('lista-empleados-admin/', views.ListEmpleadosAdmin.as_view(), name="empleados_admin"),
    path('lista-by-area/<shortname>', views.ListByAreaEmpleados.as_view(), name="empleados_por_departamento"),
    path('lista-by-trabajo/<job>', views.ListByJobEmpleado.as_view()),
    path('buscar-empleado/', views.ListEmpleadoByKword.as_view()),
    path('habilidades/<id>', views.ListHabilidadesEmpleado.as_view()),
    path('ver-detalle-empleado/<pk>', views.EmpleadoDetailView.as_view(), name="ver_empleado"),
    path('add-empleado/', views.EmpleadoCreateView.as_view(), name="add_empleado"),
    path('success/', views.SuccessView.as_view(), name='correcto'),
    path('update-empleado/<pk>', views.EmpleadoUpdateView.as_view(), name='modificar_empleado'),
    path('delete-empleado/<pk>', views.EmpleadoDeleteView.as_view(), name='eliminar_empleado'),
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

# importar paquetes para uso de archivos
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # incluimos las urls de la app departamento
    re_path('', include('applications.departamento.urls')),
    # incluimos las urls de la app persona
    re_path('', include('applications.persona.urls')),
    # incluimos las urls de la app home
    re_path('', include('applications.home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/departamento/models.py
from django.db import models

# Create your models here.

class Departamento(models.Model):
    # no es necesario crear el ID
    name = models.CharField('Nombre', max_length=50, blank=True)
    short_name = models.CharField('Nombre Corto', max_length=20, unique=True)
    anulate = models.BooleanField('Anulado', default=False)

    class Meta:
        verbose_name = 'Mi Departamento'
        verbose_name_plural = 'Areas de la empresa'
        ordering = ['-name']
        # validar que no exista una combinacion similar
        unique_together = ('name', 'short_name')

    def __str__(self):
        return str(self.id) + ' - ' + self.name + ' - ' + self.short_name

applications/departamento/forms.py
from django import forms

class NewDepartamentoForm(forms.Form):
    nombre = forms.CharField(max_length=50)
    apellido = forms.CharField(max_length=50)
    departamento = forms.CharField(max_length=50)
    shortname = forms.CharField(max_length=50)

applications/departamento/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.edit import FormView
from .forms import NewDepartamentoForm
from applications.persona.models import Empleado
from .models import Departamento

# Create your views here.

class DepartamentoListView(ListView):
    model = Departamento
    template_name = "departamento/lista.html"
    context_object_name = "departamentos"


class NewDepartamentoView(FormView):
    template_name = 'departamento/new_departamento.html'
    form_class = NewDepartamentoForm
    success_url = '/'

    def form_valid(self, form):
        print('****************** funcion form_valid *********************')
        
        # forma 1 de crear un objeto
        depa = Departamento(
            name = form.cleaned_data['departamento'],
            short_name = form.cleaned_data['shortname']
        )
        depa.save()

        # forma 2 de crear un objeto, no necesita funcion save()
        nombre = form.cleaned_data['nombre']
        apellido = form.cleaned_data['apellido']

        Empleado.objects.create(
            firt_name = nombre,
            last_name = apellido,
            job = 1,
            departamento = depa
        )
        return super(NewDepartamentoView, self).form_valid(form)

templates/departamento/lista.html
{% extends 'base.html' %}
{% block title %} Lista departamentos {% endblock title %}
{% block content %}
{% include 'includes/header.html' %}
    <div class="grid-container">
        <h1>Lista Departamentos</h1>
        <div class="cell">
            <table>
                <tbody>
                    {% for departamento in departamentos %}
                    <tr>
                        <td>{{ departamento.name }}</td>
                        <td>{{ departamento.short_name }}</td>
                        <td>
                            <a class="button warning" href="{% url 'persona_app:empleados_por_departamento' departamento.short_name %}">Ver Empleados</a>
                        </td>
                    </tr> 
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock content %}

templates/departamento/new_departamento.html
{% extends 'base.html' %}
{% block title %} Registrar Departamento {% endblock title %}
{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell"><h1>Registrar Departamento</h1></h1>
        <div class="cell callout">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                    
                <div class="grid-container">
                    <h3>Datos empleado</h3>
                    <div class="grid-x grid-padding-x">
                        <div class="medium-6 cell">
                        <label>Nombres
                            {{ form.nombre }}
                        </label>
                        </div>
                        <div class="medium-6 cell">
                        <label>Apellidos
                            {{ form.apellido }}
                        </label>
                        </div>
                    </div>
                    <h3>Datos Departamento</h3>
                    <div class="grid-x grid-padding-x">
                        <div class="medium-6 cell">
                        <label>Nombre Largo
                            {{ form.departamento }}
                        </label>
                        </div>
                        <div class="medium-6 cell">
                        <label>Nombre Corto
                            {{ form.shortname }}
                        </label>
                        </div>
                    </div>
                    <div class="grid-x grid-padding-x">
                        <div class="medium-6 cell">
                            <button class="success button" type="submit" >Guardar Nuevo Departamento    </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}